- name: Install packages in Ubuntu server
  hosts: ubuntu_servers
  vars:
    packages_to_install:
      - apache2
      - vsftpd
  
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ packages_to_install }}"
      loop_control:
        label: "{{ item }}"
