- name: Sample playbook - Hello World, AWX
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    message: "Hello World, AWX"
  
  tasks:
    - name: Print Hello World
      debug:
        var: message

    - name: Debug vars
      debug:
        var: vars

    #  run ansible-galaxy collection list
    - name: Display Ansible Galaxy collections
      ansible.builtin.command:
        cmd: ansible-galaxy collection list
      register: galaxy_collections
      
    - name: Show Ansible Galaxy collections
      ansible.builtin.debug:
        var: galaxy_collections.stdout_lines
